# 进行数据评测的目录
JUDGE_BASE_PATH: "/tmp/judge"

# 数据存放的地址
DATA_BASE_PATH: "/data"

# socket 令牌
TOKEN: token


# 从队列中取数据的等待时间 ms
COMPILE_QUEUE_DELAY_TIME: 2
JUDGE_QUEUE_DELAY_TIME: 2

REDIS:
    subscribe: redis://127.0.0.1/1
    publish: redis://127.0.0.1/1
    compile_queue: redis://127.0.0.1/1
    judge_queue: redis://127.0.0.1/1

